mutation contactCreate($input: ContactCreateInput!) {
  contactCreate(input: $input) {
    errors {
      message
    }
    contact {
      id
      identifier
      type
      alias
      transactionsCount
      createdAt
    }
  }
}
