mutation accountContactUpsert($input: AccountContactUpsertInput!) {
  accountContactUpsert(input: $input) {
    errors {
      message
    }
    contact {
      id
      identifier
      type
      alias
      transactionsCount
      createdAt
    }
  }
}
