apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: dev
  contents:
  - path: ./
    git:
      url: https://github.com/blinkbitcoin/blink.git
<<<<<<< HEAD
      ref: 9153e31a76cb564e204cf4b7d2d84a1d647dd7f8
=======
      ref: d0615a9dc31560ed608bd78b0cf3f7b066fb1869
>>>>>>> upstream/main
    includePaths:
    - dev/**/*
    excludePaths:
    - dev/bin/**/*
    - dev/.gitignore
    newRootPath: dev
- path: ./graphql
  contents:
  - path: schemas/
    git:
      url: https://github.com/blinkbitcoin/blink.git
<<<<<<< HEAD
      ref: 9153e31a76cb564e204cf4b7d2d84a1d647dd7f8
=======
      ref: d0615a9dc31560ed608bd78b0cf3f7b066fb1869
>>>>>>> upstream/main
    includePaths:
    - core/api/src/graphql/public/schema.graphql
    - core/api/src/graphql/admin/schema.graphql
    newRootPath: core/api/src/graphql
  - path: gql/
    git:
      url: https://github.com/blinkbitcoin/blink.git
<<<<<<< HEAD
      ref: 9153e31a76cb564e204cf4b7d2d84a1d647dd7f8
=======
      ref: d0615a9dc31560ed608bd78b0cf3f7b066fb1869
>>>>>>> upstream/main
    includePaths:
    - bats/gql/**/*
    newRootPath: bats/gql
