apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: dev
  contents:
  - path: ./
    git:
      url: https://github.com/blinkbitcoin/blink.git
      ref: 903e197aa2f57aba587166c2f95532d8da43eba6
    includePaths:
    - dev/**/*
    excludePaths:
    - dev/bin/**/*
    - dev/.gitignore
    newRootPath: dev
- path: ./graphql
  contents:
  - path: schemas/
    git:
      url: https://github.com/blinkbitcoin/blink.git
      ref: 903e197aa2f57aba587166c2f95532d8da43eba6
    includePaths:
    - core/api/src/graphql/public/schema.graphql
    - core/api/src/graphql/admin/schema.graphql
    newRootPath: core/api/src/graphql
  - path: gql/
    git:
      url: https://github.com/blinkbitcoin/blink.git
      ref: 903e197aa2f57aba587166c2f95532d8da43eba6
    includePaths:
    - bats/gql/**/*
    newRootPath: bats/gql
