query accountDetailsByAccountId($accountId: ID!) {
  accountDetailsByAccountId(accountId: $accountId) {
    id
    level
    owner {
      id
      phone
      email {
        address
        verified
      }
    }
  }
}
