query accountDetailsByUserPhone($phone: Phone!) {
  accountDetailsByUserPhone(phone: $phone) {
    id
    username
    level
    status
    merchants {
      id
      title
      coordinates {
        latitude
        longitude
      }
      createdAt
      validated
      username
    }
    owner {
      id
      language
      phone
      email {
        address
        verified
      }
      createdAt
    }
    wallets {
      id
      walletCurrency
      accountId
      balance
      pendingIncomingBalance
    }
    createdAt
  }
}

query accountDetailsByAccountId($accountId: ID!) {
  accountDetailsByAccountId(accountId: $accountId) {
    id
    username
    level
    status
    merchants {
      id
      title
      coordinates {
        latitude
        longitude
      }
      createdAt
      validated
      username
    }
    owner {
      id
      language
      phone
      email {
        address
        verified
      }
      createdAt
    }
    wallets {
      id
      walletCurrency
      accountId
      balance
      pendingIncomingBalance
    }
    createdAt
  }
}

query accountDetailsByEmail($email: EmailAddress!) {
  accountDetailsByEmail(email: $email) {
    id
    username
    level
    status
    merchants {
      id
      title
      coordinates {
        latitude
        longitude
      }
      createdAt
      validated
      username
    }
    owner {
      id
      language
      phone
      email {
        address
        verified
      }
      createdAt
    }
    wallets {
      id
      walletCurrency
      accountId
      balance
      pendingIncomingBalance
    }
    createdAt
  }
}

mutation merchantMapDelete($input: MerchantMapDeleteInput!) {
  merchantMapDelete(input: $input) {
    errors {
      message
    }
  }
}

mutation merchantMapValidate($input: MerchantMapValidateInput!) {
  merchantMapValidate(input: $input) {
    errors {
      message
    }
  }
}

mutation accountUpdateLevel($input: AccountUpdateLevelInput!) {
  accountUpdateLevel(input: $input) {
    errors {
      message
    }
    accountDetails {
      id
      username
      level
      status
      merchants {
        id
        title
        coordinates {
          latitude
          longitude
        }
        createdAt
        validated
        username
      }
      owner {
        id
        language
        phone
        email {
          address
          verified
        }
        createdAt
      }
      wallets {
        id
        walletCurrency
        accountId
        balance
        pendingIncomingBalance
      }
      createdAt
    }
  }
}

mutation accountUpdateStatus($input: AccountUpdateStatusInput!) {
  accountUpdateStatus(input: $input) {
    errors {
      message
    }
    accountDetails {
      id
      username
      level
      status
      merchants {
        id
        title
        coordinates {
          latitude
          longitude
        }
        createdAt
        validated
        username
      }
      owner {
        id
        language
        phone
        email {
          address
          verified
        }
        createdAt
      }
      wallets {
        id
        walletCurrency
        accountId
        balance
        pendingIncomingBalance
      }
      createdAt
    }
  }
}

query accountDetailsByUsername($username: Username!) {
  accountDetailsByUsername(username: $username) {
    id
    username
    level
    status
    merchants {
      id
      title
      coordinates {
        latitude
        longitude
      }
      createdAt
      validated
      username
    }
    owner {
      id
      language
      phone
      email {
        address
        verified
      }
      createdAt
    }
    wallets {
      id
      walletCurrency
      accountId
      balance
      pendingIncomingBalance
    }
    createdAt
  }
}

query lightningInvoice($hash: PaymentHash!) {
  lightningInvoice(hash: $hash) {
    createdAt
    confirmedAt
    description
    expiresAt
    isSettled
    received
    request
    secretPreImage
  }
}

query lightningPayment($hash: PaymentHash!) {
  lightningPayment(hash: $hash) {
    createdAt
    confirmedAt
    status
    amount
    roundedUpFee
    revealedPreImage
    request
    destination
  }
}

query transactionsByHash($hash: PaymentHash!) {
  transactionsByHash(hash: $hash) {
    id
    initiationVia {
      __typename
      ... on InitiationViaIntraLedger {
        counterPartyWalletId
        counterPartyUsername
      }
      ... on InitiationViaLn {
        paymentHash
      }
      ... on InitiationViaOnChain {
        address
      }
    }
    settlementVia {
      __typename
      ... on SettlementViaIntraLedger {
        counterPartyWalletId
        counterPartyUsername
      }
      ... on SettlementViaLn {
        paymentSecret
      }
      ... on SettlementViaOnChain {
        transactionHash
      }
    }
    settlementAmount
    settlementFee
    settlementPrice {
      base
      offset
      currencyUnit
      formattedAmount
    }
    direction
    status
    memo
    createdAt
  }
}

query transactionById($id: ID!) {
  transactionById(id: $id) {
    id
    initiationVia {
      __typename
      ... on InitiationViaIntraLedger {
        counterPartyWalletId
        counterPartyUsername
      }
      ... on InitiationViaLn {
        paymentHash
      }
      ... on InitiationViaOnChain {
        address
      }
    }
    settlementVia {
      __typename
      ... on SettlementViaIntraLedger {
        counterPartyWalletId
        counterPartyUsername
      }
      ... on SettlementViaLn {
        paymentSecret
      }
      ... on SettlementViaOnChain {
        transactionHash
      }
    }
    settlementAmount
    settlementFee
    settlementPrice {
      base
      offset
      currencyUnit
      formattedAmount
    }
    direction
    status
    memo
    createdAt
  }
}

query merchantsPendingApproval {
  merchantsPendingApproval {
    id
    title
    coordinates {
      latitude
      longitude
    }
    createdAt
    validated
    username
  }
}

query inactiveMerchants {
  inactiveMerchants {
    id
    title
    coordinates {
      latitude
      longitude
    }
    createdAt
    validated
    username
  }
}

query filteredUserCount($phoneCountryCodesFilter: [CountryCode!], $userIdsFilter: [ID!]) {
  filteredUserCount(
    phoneCountryCodesFilter: $phoneCountryCodesFilter
    userIdsFilter: $userIdsFilter
  )
}

mutation marketingNotificationTrigger($input: MarketingNotificationTriggerInput!) {
  marketingNotificationTrigger(input: $input) {
    errors {
      message
    }
    success
  }
}

query notificationMessages(
  $username: String
  $limit: Int
  $offset: Int
  $status: NotificationMessageStatus
  $updatedAtFrom: Int
  $updatedAtTo: Int
) {
  notificationMessages(
    username: $username
    limit: $limit
    offset: $offset
    status: $status
    updatedAtFrom: $updatedAtFrom
    updatedAtTo: $updatedAtTo
  ) {
    id
    sentBy
    status
    updatedAt
    username
  }
}

query notificationTemplates {
  notificationTemplates {
    body
    iconName
    id
    languageCode
    name
    shouldAddToBulletin
    shouldAddToHistory
    shouldSendPush
    title
    deeplinkAction
    deeplinkScreen
    externalUrl
  }
}

query notificationByTemplateId($id: ID!) {
  notificationByTemplateId(id: $id) {
    id
    name
    languageCode
    title
    body
    iconName
    shouldSendPush
    shouldAddToHistory
    shouldAddToBulletin
    deeplinkAction
    deeplinkScreen
    externalUrl
  }
}

mutation notificationMessageCreate($input: NotificationMessageCreateInput!) {
  notificationMessageCreate(input: $input) {
    errors {
      message
    }
  }
}

mutation notificationMessageUpdateStatus($input: NotificationMessageUpdateStatusInput!) {
  notificationMessageUpdateStatus(input: $input) {
    errors {
      message
    }
  }
}

mutation notificationTemplateCreate($input: NotificationTemplateCreateInput!) {
  notificationTemplateCreate(input: $input) {
    errors {
      message
    }
  }
}

mutation notificationTemplateUpdate($input: NotificationTemplateUpdateInput!) {
  notificationTemplateUpdate(input: $input) {
    success
    errors {
      message
      code
      path
    }
  }
}

mutation notificationTemplateDelete($input: NotificationTemplateDeleteInput!) {
  notificationTemplateDelete(input: $input) {
    success
    errors {
      message
      code
      path
    }
  }
}

query notificationMessageHistory($id: ID!) {
  notificationMessageHistory(id: $id) {
    id
    status
    createdAt
  }
}
